<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = 'places';
        $now = Carbon::now()->format('Y-m-d H:i:s');
        $places = [
            ['cidade' => 'Recife' , 'bairro' => 'Aflitos', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Afogados', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Agua Fria', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Alto do Mandu', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Alto Jose Bonifacio', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Alto Jose do Pinho', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Alto Santa Teresinha', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Apipucos', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Areias', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Arruda', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Barro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Beberibe', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Boa Viagem', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Boa Vista', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Bomba do Hemeterio', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Bongi', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Brasilia Teimosa', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Brejo da Guabiraba', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Brejo de Beberibe', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Cabanga', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Caçote', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Cajueiro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Campina do Barreto', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Campo Grande', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Casa Amarela', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Casa Forte', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Caxanga', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Cidade Universitaria', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Coelhos', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Cohab', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Comunidade do Pilar', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Coque', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Coqueiral', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Cordeiro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Corrego do jenipapo', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Curado', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Encruzilhada', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Engenho do Meio', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Entra Apulso', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Espinheiro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Estancia', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Fundao', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Graças', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Guabiraba', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Hipodromo', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Ibura', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Ilha Joana Bezerra', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Ilha do Leite', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Ilha do Retiro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Imbiribeira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Ipsep', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Iputinga', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Jaqueira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Jardim Sao Paulo', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Jiquia', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Jordao', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Linha do Tiro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Macaxeira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Madalena', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Mangabeira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Mangueira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Monteiro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Morro da conceiçao', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Mustardinha', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Nova Descoberta', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Paissandu', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Parnamirim', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Passarinho', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Pau Ferro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Peixinhos', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Pina', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Poço de Panela', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => "Ponte D'Uchoa", 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Ponto de Parada', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Porto da Madeira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Prado', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Recife', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Rosarinho', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'San Martin', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Sancho', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Santana', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Santo Amaro', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Santo Antonio', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Sao Jose', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Setubal', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Sitio dos Pintos', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Soledade', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Tamarineira', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Tejipio', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Torre', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Torreao', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Torroes', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Toto', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Varzea', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Vasco da Gama', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'vila Tamandare', 'created_at' => $now, 'updated_at' =>$now],
            ['cidade' => 'Recife' , 'bairro' => 'Zumbi', 'created_at' => $now, 'updated_at' =>$now],
        ];

        DB::table($table)->insert($places);
    }
}
